version: '2.0'
services:
  node:
    build: 
      context: ../
      dockerfile: ./docker/nodejs/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
    environment:
      PORT: 80
